// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/useful/common/protobuf/Command.proto

package com.useful.common.protobuf;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   **
   * 指令类型
   * </pre>
   *
   * Protobuf enum {@code CommandType}
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     **
     * 验证
     * </pre>
     *
     * <code>AUTH = 0;</code>
     */
    AUTH(0),
    /**
     * <pre>
     **
     * 验证返回
     * </pre>
     *
     * <code>AUTH_BACK = 1;</code>
     */
    AUTH_BACK(1),
    /**
     * <pre>
     **
     * ping
     * </pre>
     *
     * <code>PING = 2;</code>
     */
    PING(2),
    /**
     * <pre>
     **
     * pong
     * </pre>
     *
     * <code>PONG = 3;</code>
     */
    PONG(3),
    /**
     * <pre>
     **
     * echo
     * </pre>
     *
     * <code>ECHO = 4;</code>
     */
    ECHO(4),
    /**
     * <pre>
     **
     * echo返回
     * </pre>
     *
     * <code>ECHO_BACK = 5;</code>
     */
    ECHO_BACK(5),
    /**
     * <pre>
     **
     * REQUEST
     * </pre>
     *
     * <code>REQUEST = 6;</code>
     */
    REQUEST(6),
    /**
     * <pre>
     **
     * RESPONSE
     * </pre>
     *
     * <code>RESPONSE = 7;</code>
     */
    RESPONSE(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     **
     * 验证
     * </pre>
     *
     * <code>AUTH = 0;</code>
     */
    public static final int AUTH_VALUE = 0;
    /**
     * <pre>
     **
     * 验证返回
     * </pre>
     *
     * <code>AUTH_BACK = 1;</code>
     */
    public static final int AUTH_BACK_VALUE = 1;
    /**
     * <pre>
     **
     * ping
     * </pre>
     *
     * <code>PING = 2;</code>
     */
    public static final int PING_VALUE = 2;
    /**
     * <pre>
     **
     * pong
     * </pre>
     *
     * <code>PONG = 3;</code>
     */
    public static final int PONG_VALUE = 3;
    /**
     * <pre>
     **
     * echo
     * </pre>
     *
     * <code>ECHO = 4;</code>
     */
    public static final int ECHO_VALUE = 4;
    /**
     * <pre>
     **
     * echo返回
     * </pre>
     *
     * <code>ECHO_BACK = 5;</code>
     */
    public static final int ECHO_BACK_VALUE = 5;
    /**
     * <pre>
     **
     * REQUEST
     * </pre>
     *
     * <code>REQUEST = 6;</code>
     */
    public static final int REQUEST_VALUE = 6;
    /**
     * <pre>
     **
     * RESPONSE
     * </pre>
     *
     * <code>RESPONSE = 7;</code>
     */
    public static final int RESPONSE_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CommandType forNumber(int value) {
      switch (value) {
        case 0: return AUTH;
        case 1: return AUTH_BACK;
        case 2: return PING;
        case 3: return PONG;
        case 4: return ECHO;
        case 5: return ECHO_BACK;
        case 6: return REQUEST;
        case 7: return RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CommandType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.useful.common.protobuf.Command.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CommandType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CommandType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(com/useful/common/protobuf/Command.pro" +
      "to*n\n\013CommandType\022\010\n\004AUTH\020\000\022\r\n\tAUTH_BACK" +
      "\020\001\022\010\n\004PING\020\002\022\010\n\004PONG\020\003\022\010\n\004ECHO\020\004\022\r\n\tECHO" +
      "_BACK\020\005\022\013\n\007REQUEST\020\006\022\014\n\010RESPONSE\020\007B%\n\032co" +
      "m.useful.common.protobufB\007Commandb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
