# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    port: 9003
    connection-timeout: 5000ms

spring:
  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/highest_flow?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456789
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    date-format: "YYYY-MM-dd HH:mm:ss"
    serialization:
      write_dates_as_timestamps: false

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

threadpool:
  core-pool-size: 6000
  max-pool-size: 9000
  queue-capacity: 3000

ranking:
  # 每个直播间的最大线程数
  unit-pool-size: 300
  # 同时刷的最多直播间数
  max-sync-count: 20

sign:
  prefix: gaoji
  suffix: yinliu
  method: md5
  #http://119.45.148.200:9999/xdata
  #http://localhost:9999/xdata
  url: http://119.45.148.200:9999/xdata

secure:
  key: 1234!@#$

license:
  key: 1234!@#$

taobaolive:
  simulate: false

http:
  inspect: true